version: "3"
services:
  nginx:
    ports:
      - "80:80"
  node-app:
    deploy:
      replicas: 8
      restart_policy:
        condition: any
      update_config:
        parallelism: 2
        delay: 15s
    build:
      context: .
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
      - MONGO_IP=mongo
      - MONGO_PORT=27017
      - MONGO_USER=lvl162
      - MONGO_PASSWORD=1622000
      - SESSION_SECRET=anhloithatsudeptraivodichkhapvutru
    command: node index.js
