version: "3"
services:
  nginx:
    ports:
      - "3000:80"
  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    # ports:
    #   - '3000:3000'
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_IP=mongo
      - MONGO_PORT=27017
      - MONGO_USER=lvl162
      - MONGO_PASSWORD=1622000
      - SESSION_SECRET=anhloithatsudeptraivodichkhapvutru
    command: npm run dev
